language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
    - example/node_modules
script:
  - npm run build
  - npm run --prefix example build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    on:
      branch: master
    local_dir: example/build
